// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViAiStudio.Infrastructure.Persistence;

#nullable disable

namespace ViAiStudio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ViAiStudioDbContext))]
    [Migration("20260813224611_AddSpecificationAuthoringPipeline")]
    partial class AddSpecificationAuthoringPipeline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ViAiStudio.Domain.Entities.AiCallLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GenerationVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Requests")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SpecificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TokensIn")
                        .HasColumnType("integer");

                    b.Property<int>("TokensOut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationId");

                    b.ToTable("AiCallLogs");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.AiModelConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("AiModelConfigs");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.Generation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveStorageKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("FileTree")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SpecificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Stack", "ViAiStudio.Domain.Entities.Generation.Stack#TechStack", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Backend")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("stack_backend");

                            b1.Property<string>("Database")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("stack_database");

                            b1.Property<string>("Infra")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("stack_infra");

                            b1.Property<string>("Ui")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("stack_ui");

                            b1.Property<string>("UiStyle")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("stack_ui_style");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SpecificationId", "Version")
                        .IsUnique();

                    b.ToTable("Generations");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.Specification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentPaths")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DocumentsArchiveStorageKey")
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<string>("SpecMarkdown")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Stack", "ViAiStudio.Domain.Entities.Specification.Stack#TechStack", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Backend")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("stack_backend");

                            b1.Property<string>("Database")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("stack_database");

                            b1.Property<string>("Infra")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("stack_infra");

                            b1.Property<string>("Ui")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("stack_ui");

                            b1.Property<string>("UiStyle")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("stack_ui_style");
                        });

                    b.HasKey("Id");

                    b.ToTable("Specifications");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DependsOn")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Generates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provides")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SpecId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SpecificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationId", "Path")
                        .IsUnique();

                    b.ToTable("SpecificationDocuments");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationGenerationBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllocatedIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("BatchIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FilesWritten")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "BatchIndex")
                        .IsUnique();

                    b.ToTable("SpecificationGenerationBatches");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationGenerationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SpecificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationId");

                    b.ToTable("SpecificationGenerationRuns");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationIntakeSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Compliance")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ConflictsResolved")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Deployables")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Environments")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Frontend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrontendRequirements")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FunctionalAreas")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("IdentityFeatures")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("IdentityModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImpliedDecisions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PrimaryDatabase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductShape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rigour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SpecificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("StillUnknown")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SupportingInfrastructure")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantIsolation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationId")
                        .IsUnique();

                    b.ToTable("SpecificationIntakeSheets");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationInterviewAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AiExpandedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<string>("DefaultHint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionIndex")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoundIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpecificationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("UsedDefault")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationId", "RoundIndex", "QuestionIndex")
                        .IsUnique();

                    b.ToTable("SpecificationInterviewAnswers");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckedItems")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("GeneratedText")
                        .HasColumnType("text");

                    b.Property<int>("PhaseIndex")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedKeywords")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SpecificationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationId", "PhaseIndex")
                        .IsUnique();

                    b.ToTable("SpecificationPhases", (string)null);
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationPromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SpecificationPromptTemplates");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationValidationIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("SpecificationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationId");

                    b.ToTable("SpecificationValidationIssues");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.TaskRouting", b =>
                {
                    b.Property<string>("Task")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("AiModelConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Task");

                    b.HasIndex("AiModelConfigId");

                    b.ToTable("TaskRoutings");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.AiCallLog", b =>
                {
                    b.HasOne("ViAiStudio.Domain.Entities.Specification", null)
                        .WithMany()
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.Generation", b =>
                {
                    b.HasOne("ViAiStudio.Domain.Entities.Specification", null)
                        .WithMany("Generations")
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationDocument", b =>
                {
                    b.HasOne("ViAiStudio.Domain.Entities.Specification", null)
                        .WithMany("Documents")
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationGenerationBatch", b =>
                {
                    b.HasOne("ViAiStudio.Domain.Entities.SpecificationGenerationRun", null)
                        .WithMany("Batches")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationGenerationRun", b =>
                {
                    b.HasOne("ViAiStudio.Domain.Entities.Specification", null)
                        .WithMany("GenerationRuns")
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationIntakeSheet", b =>
                {
                    b.HasOne("ViAiStudio.Domain.Entities.Specification", null)
                        .WithOne("Intake")
                        .HasForeignKey("ViAiStudio.Domain.Entities.SpecificationIntakeSheet", "SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationInterviewAnswer", b =>
                {
                    b.HasOne("ViAiStudio.Domain.Entities.Specification", null)
                        .WithMany("InterviewAnswers")
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationPhase", b =>
                {
                    b.HasOne("ViAiStudio.Domain.Entities.Specification", null)
                        .WithMany("Phases")
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.TaskRouting", b =>
                {
                    b.HasOne("ViAiStudio.Domain.Entities.AiModelConfig", null)
                        .WithMany()
                        .HasForeignKey("AiModelConfigId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("ViAiStudio.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("ViAiStudio.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("ViAiStudio.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViAiStudio.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.Specification", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("GenerationRuns");

                    b.Navigation("Generations");

                    b.Navigation("Intake");

                    b.Navigation("InterviewAnswers");

                    b.Navigation("Phases");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.SpecificationGenerationRun", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("ViAiStudio.Domain.Entities.User", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
