// Suggested keyword chips per wizard phase (design/README.md screen 8).
// Presentational only -- these are toggle suggestions the user picks from,
// not backed by a catalog on the Api; SpecificationPhase.selectedKeywords
// just stores whichever subset (any strings) the user has toggled on.
export const KEYWORD_BANK: string[][] = [
  ["Increase online sales", "Support small retailers", "Fast store launch", "Brand consistency", "Mobile-first shopping", "Loyal customer base"],
  [
    "1. Authentication", "2. Authorization, roles & permissions", "3. User & profile management",
    "4. Multi-tenancy, organizations & teams", "5. Onboarding, invitations & user lifecycle",
    "6. CRUD, querying, filtering & pagination", "7. Validation & error handling",
    "8. Data access, migrations & seeding", "9. Caching", "10. File storage, upload & media processing",
    "11. Search", "12. Notifications (email, SMS, push, in-app)", "13. Real-time communication",
    "14. Background jobs & scheduling", "15. Messaging, events & integration between services",
    "16. Workflows, approvals & business process automation", "17. Reporting, analytics, exports & document generation",
    "18. Data import & bulk operations", "19. Audit logging & change history", "20. Soft delete, archiving & data retention",
    "21. Comments, activity feeds, mentions & collaboration", "22. Ratings, reviews, moderation & user-generated content",
    "23. Payments, subscriptions & usage metering", "24. Outbound webhooks & third-party integrations",
    "25. Public API & developer experience", "26. Feature flags, configuration-driven behaviour & experimentation",
    "27. Configuration, secrets & environment management", "28. Localization, internationalization & time",
    "29. Rate limiting, quotas & abuse prevention", "30. Security hardening", "31. Privacy, GDPR & compliance",
    "32. Logging, monitoring & observability", "33. Health checks, readiness & operational endpoints",
    "34. Backups, disaster recovery & business continuity", "35. Admin panel, support tooling & impersonation",
    "36. Testing strategy", "37. CI/CD & release management", "38. Containerization, orchestration & infrastructure",
    "39. Performance & scaling", "40. Frontend delivery, accessibility & SEO", "41. AI features",
    "42. Documentation & developer experience", "43. Cost management (FinOps)",
  ],
  ["Guest checkout", "Wishlist support", "Saved addresses", "Order history view", "Quick reorder", "Product reviews"],
  ["Customer profile", "Order lifecycle", "Inventory levels", "Payment records", "Shipment tracking", "Coupon rules"],
  ["Cart persistence", "Payment gateway", "Email notifications", "Sales reporting", "Admin dashboard", "Discount codes"],
  ["Simple checkout flow", "Clear product imagery", "Fast search results", "Minimal cart steps", "Guided onboarding", "Trust badges"],
  ["Dark mode toggle", "Responsive grid layout", "Sticky add-to-cart", "Skeleton loading states", "Empty cart illustration", "Inline form validation"],
  ["Next.js frontend", ".NET Web API", "PostgreSQL database", "Redis caching", "Blob storage", "Server components"],
  ["Indexed product search", "Order history table", "Soft delete records", "Audit timestamps", "Normalized schema", "EF Core migrations"],
  ["REST endpoints", "JWT auth header", "Paginated responses", "Idempotent payments", "Versioned API", "Webhook support"],
  ["Two-factor login", "Encrypted card data", "Role-based access", "Rate limited endpoints", "Audit trail", "Secrets vault"],
  ["Auto-scaling containers", "Zero-downtime deploys", "Centralized logging", "Automated backups", "Staging environment", "Disaster recovery plan"],
  ["Feature branch workflow", "Code review process", "Shared component library", "Type-safe API client", "Seed test data", "Continuous integration"],
  ["Checkout test coverage", "Load tested payments", "Accessibility audit", "Cross-browser testing", "Regression suite", "Bug triage process"],
  ["Blue-green deployment", "Production monitoring", "Alert thresholds", "Rollback plan", "Uptime dashboard", "Release notes"],
];
